[WIP] Adds Prometheus metrics to ODIS combiner daemon (Odis Combiner to k8s)
celo-org/social-connect pull request #49
Opened 2023-09-29 10:32 UTC by alvarof2

### Description

- Adds a new endpoint /metrics to ODIS combiner to expose metrics.
Docker images:
- Moves dockerfiles/phone-number-privacy/Dockerfile to dockerfiles/phone-number-privacy/Dockerfile-signer for the signer container.
- Adds dockerfiles/phone-number-privacy/Dockerfile-combiner for the combiner container.
- Modifies cloudbuild.yaml accordingly.

Adds the following counters and histograms:
- Counter `combiner_requests_total`
- Counter `combiner_responses_total`
- Counter `combiner_blockchain_errors_total`
- Counter `combiner_bls_compute_errors_total`
- Counter `combiner_endpoint_handler_errors_total`
- Counter `combiner_not_enough_sig_errors_total`
- Counter `combiner_sig_request_errors_total`
- Counter `combiner_sig_response_errors_total`
- Counter `combiner_sig_inconsistency_errors_total`
- Counter `combiner_sig_response_total`
- Counter `combiner_unknown_errors_total`
- Counter `combiner_warnings_total`
- Histogram `combiner_endpoint_latency`
- Histogram `combiner_full_node_latency`
- Histogram `combiner_signer_latency`

I couldn't find a way to create the event loop lag Histogram  :( 

Current metrics can be seen here: https://clabs.grafana.net/goto/2qF4RaWSg?orgId=1

### Other changes

_Describe any minor or "drive-by" changes here._

### Tested

_An explanation of how the changes were tested or an explanation as to why they don't need to be._

### Related issues

- Fixes #[issue number here]

### Backwards compatibility

_Brief explanation of why these changes are/are not backwards compatible._

### Documentation

_The set of community facing docs that have been added/modified because of this change_

2023-10-02 14:23 UTC, jcortejoso commented
I'd be in favor of sunsetting cloud-build and replacing by GitHub Actions.

Happy to address that in a separate PR.

2023-10-05 12:15 UTC, aaronmgdr requested changes
Reminder to add a changeset

2023-10-13 14:30 UTC, alecps approved these changes
Looks great, thanks!! Before I merge the odisCombinerK8s branch I'll go through one last time and ensure we aren't double counting errors anywhere

2023-10-13 14:30 UTC, alecps commented on packages/phone-number-privacy/combiner/src/common/handlers.ts
> +          Counters.errors.labels(req.url).inc()
This is double counting I believe

2023-10-13 14:30 UTC, alecps commented on packages/phone-number-privacy/combiner/src/common/web3/contracts.ts
> +      Counters.errors.labels('getDEK').inc()
Is there a preset for this?

2023-10-13 14:30 UTC, alecps commented on packages/phone-number-privacy/combiner/src/domain/endpoints/disable/action.ts
> +      Counters.warnings.labels(request.url, WarningMessage.INVALID_INPUT).inc()
should this go in errorResult?

2023-10-13 14:31 UTC, merged